version: "3"

services:
  web:
    stdin_open: true
    tty: true
    platform: linux/amd64 # Just to do compatible with arm64 mac m1 for example 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: development
      MYSQL_USER: the_user
      MYSQL_PASSWORD: the_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /:/var/lib/mysql_database

volumes:
  mysql_data: